;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        cua--prefix-override-handler
        cua-cut-region
        cua-paste
        evilnc-comment-or-uncomment-lines
        helm-show-kill-ring
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-fill-paragraph
        org-kill-line
        org-metaleft
        org-self-insert-command
        orgtbl-self-insert-command
        sbw/unfill-paragraph
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-unwrap-sexp
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-select-next-thing-exchange
        ))

(setq mc/cmds-to-run-once
      '(
        cua-scroll-up
        helm-M-x
        keyboard-escape-quit
        mouse-yank-primary
        multiple-cursors-mode
        sbw/hydra-multiple-cursors/body
        sbw/hydra-multiple-cursors/mc/mark-next-like-this
        sbw/hydra-multiple-cursors/mc/mark-previous-like-this
        sbw/hydra-multiple-cursors/mc/skip-to-next-like-this
        sbw/hydra-multiple-cursors/mc/skip-to-previous-like-this
        sbw/hydra-multiple-cursors/mc/unmark-next-like-this
        sbw/hydra-multiple-cursors/mc/unmark-previous-like-this
        sbw/hydra-multiple-cursors/nil
        undefined
        ))
