;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-cut-region
        sp-backward-delete-char
        sp-delete-char
        sp-forward-slurp-sexp
        sp-select-next-thing-exchange
        ))

(setq mc/cmds-to-run-once
      '(
        ))
